// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins.Create;
using Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins.DeleteCode;
using Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins.Latest;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins
{
    /// <summary>
    /// Builds and executes requests for operations under \sources\{sourceId}\live-plugins
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LivePluginsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins.Create.CreateRequestBuilder Create
        {
            get => new global::Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deleteCode property</summary>
        public global::Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins.DeleteCode.DeleteCodeRequestBuilder DeleteCode
        {
            get => new global::Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins.DeleteCode.DeleteCodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The latest property</summary>
        public global::Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins.Latest.LatestRequestBuilder Latest
        {
            get => new global::Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins.Latest.LatestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins.LivePluginsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LivePluginsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sources/{sourceId}/live-plugins", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Sources.Item.LivePlugins.LivePluginsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LivePluginsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sources/{sourceId}/live-plugins", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
