// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Segment.OpenApiClient.Destination.Item.Filters;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Segment.OpenApiClient.Destination.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \destination\{destinationId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDestinationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The filters property</summary>
        public global::Soenneker.Segment.OpenApiClient.Destination.Item.Filters.FiltersRequestBuilder Filters
        {
            get => new global::Soenneker.Segment.OpenApiClient.Destination.Item.Filters.FiltersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Destination.Item.WithDestinationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDestinationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/destination/{destinationId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Destination.Item.WithDestinationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDestinationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/destination/{destinationId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
