// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// A class that encapsulates the complete activation output with full details.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivationOutput : IParsable
    {
        /// <summary>Activation name. For Warehouse Destinations, this is the table name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActivationName { get; set; }
#nullable restore
#else
        public string ActivationName { get; set; }
#endif
        /// <summary>Determines when an event is sent to the Destination.Possible values:Audience Entered: Sends an event when a profile enters the audience.Audience Exited: Sends an event when a profile exits the audience.Audience Membership Changed: Sends an event for both profile entries and profile exits.Entity Added: Sends an event when an entity enters the audience.Entity Removed: Sends an event when an entity exits the audience.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActivationType { get; set; }
#nullable restore
#else
        public string ActivationType { get; set; }
#endif
        /// <summary>The audience id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudienceId { get; set; }
#nullable restore
#else
        public string AudienceId { get; set; }
#endif
        /// <summary>The connection id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionId { get; set; }
#nullable restore
#else
        public string ConnectionId { get; set; }
#endif
        /// <summary>The action and data mapping configured for the Destination. Only present for Action Destinations.Action id: The action performed on the Destination.Settings/Mapping: How event data populates specific fields in the Destination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ActivationOutputDestinationMapping? DestinationMapping { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ActivationOutputDestinationMapping DestinationMapping { get; set; }
#endif
        /// <summary>Human-readable label for the activation. Only present for Warehouse Destinations that have a display name configured. When null, the activationName serves as the label.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Activation Enabled Status.</summary>
        public bool? Enabled { get; set; }
        /// <summary>The activation id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Indicates if a full resync is currently pending or in progress.</summary>
        public bool? PerformResync { get; set; }
        /// <summary>The data points used to enrich the event. Defines which profile traits and/or entity properties are included in the event sent to the Destination.For Action Destinations, any traits or properties specified here must also be included in the destinationMapping to define which Destination fields should be populated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ActivationOutputPersonalization? Personalization { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ActivationOutputPersonalization Personalization { get; set; }
#endif
        /// <summary>The space id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpaceId { get; set; }
#nullable restore
#else
        public string SpaceId { get; set; }
#endif
        /// <summary>The WORKSPACE id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceId { get; set; }
#nullable restore
#else
        public string WorkspaceId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.ActivationOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.ActivationOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.ActivationOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activationName", n => { ActivationName = n.GetStringValue(); } },
                { "activationType", n => { ActivationType = n.GetStringValue(); } },
                { "audienceId", n => { AudienceId = n.GetStringValue(); } },
                { "connectionId", n => { ConnectionId = n.GetStringValue(); } },
                { "destinationMapping", n => { DestinationMapping = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ActivationOutputDestinationMapping>(global::Soenneker.Segment.OpenApiClient.Models.ActivationOutputDestinationMapping.CreateFromDiscriminatorValue); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "performResync", n => { PerformResync = n.GetBoolValue(); } },
                { "personalization", n => { Personalization = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ActivationOutputPersonalization>(global::Soenneker.Segment.OpenApiClient.Models.ActivationOutputPersonalization.CreateFromDiscriminatorValue); } },
                { "spaceId", n => { SpaceId = n.GetStringValue(); } },
                { "workspaceId", n => { WorkspaceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("activationName", ActivationName);
            writer.WriteStringValue("activationType", ActivationType);
            writer.WriteStringValue("audienceId", AudienceId);
            writer.WriteStringValue("connectionId", ConnectionId);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ActivationOutputDestinationMapping>("destinationMapping", DestinationMapping);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("performResync", PerformResync);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ActivationOutputPersonalization>("personalization", Personalization);
            writer.WriteStringValue("spaceId", SpaceId);
            writer.WriteStringValue("workspaceId", WorkspaceId);
        }
    }
}
#pragma warning restore CS0618
