// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>Denotes the type of audience product.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AudienceSummaryWithAudienceTypeAndLookbackAudienceType
    {
        [EnumMember(Value = "ACCOUNTS")]
        #pragma warning disable CS1591
        Accounts,
        #pragma warning restore CS1591
        [EnumMember(Value = "LINKED")]
        #pragma warning disable CS1591
        Linked,
        #pragma warning restore CS1591
        [EnumMember(Value = "USERS")]
        #pragma warning disable CS1591
        Users,
        #pragma warning restore CS1591
    }
}
