// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>The cadence type on which the audience&apos;s membership is computed.If &apos;BATCH&apos;, the audience is computed on a periodic basis.If &apos;REALTIME&apos;, the audience is continously computed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AudienceComputeCadenceType
    {
        [EnumMember(Value = "BATCH")]
        #pragma warning disable CS1591
        Batch,
        #pragma warning restore CS1591
        [EnumMember(Value = "REALTIME")]
        #pragma warning disable CS1591
        Realtime,
        #pragma warning restore CS1591
    }
}
