// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>Status for the audience preview.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AudiencePreviewStatus
    {
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "RUNNING")]
        #pragma warning disable CS1591
        Running,
        #pragma warning restore CS1591
    }
}
