// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>The unit type for the count(s) being returned.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AudienceSizeType
    {
        [EnumMember(Value = "ACCOUNTS")]
        #pragma warning disable CS1591
        Accounts,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENTITIES")]
        #pragma warning disable CS1591
        Entities,
        #pragma warning restore CS1591
        [EnumMember(Value = "USERS")]
        #pragma warning disable CS1591
        Users,
        #pragma warning restore CS1591
    }
}
