// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Batch get response.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BatchQueryMessagingSubscriptionsForSpaceAlphaOutput : IParsable
    {
        /// <summary>General errors when making the request such as invalid payload or wrong http method errors.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseError>? Errors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseError> Errors { get; set; }
#endif
        /// <summary>Validation errors due to invalid types or email/phone numbers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.GetMessagingSubscriptionFailureResponse>? Failures { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.GetMessagingSubscriptionFailureResponse> Failures { get; set; }
#endif
        /// <summary>Information about the pagination of this response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.BatchQueryMessagingSubscriptionsForSpaceAlphaOutputPagination? Pagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.BatchQueryMessagingSubscriptionsForSpaceAlphaOutputPagination Pagination { get; set; }
#endif
        /// <summary>Array of successful subscription status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.GetMessagingSubscriptionSuccessResponse>? Successes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.GetMessagingSubscriptionSuccessResponse> Successes { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.BatchQueryMessagingSubscriptionsForSpaceAlphaOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.BatchQueryMessagingSubscriptionsForSpaceAlphaOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.BatchQueryMessagingSubscriptionsForSpaceAlphaOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseError>(global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseError.CreateFromDiscriminatorValue)?.AsList(); } },
                { "failures", n => { Failures = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.GetMessagingSubscriptionFailureResponse>(global::Soenneker.Segment.OpenApiClient.Models.GetMessagingSubscriptionFailureResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pagination", n => { Pagination = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.BatchQueryMessagingSubscriptionsForSpaceAlphaOutputPagination>(global::Soenneker.Segment.OpenApiClient.Models.BatchQueryMessagingSubscriptionsForSpaceAlphaOutputPagination.CreateFromDiscriminatorValue); } },
                { "successes", n => { Successes = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.GetMessagingSubscriptionSuccessResponse>(global::Soenneker.Segment.OpenApiClient.Models.GetMessagingSubscriptionSuccessResponse.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseError>("errors", Errors);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.GetMessagingSubscriptionFailureResponse>("failures", Failures);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.BatchQueryMessagingSubscriptionsForSpaceAlphaOutputPagination>("pagination", Pagination);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.GetMessagingSubscriptionSuccessResponse>("successes", Successes);
        }
    }
}
#pragma warning restore CS0618
