// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// CancelReverseETLSyncForModelOutput either will return an error or a &quot;CANCELLING&quot; status.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CancelReverseEtlSyncForModelOutput : IParsable
    {
        /// <summary>A place holder for a machine-friendly category for an error, if applicable.- &quot;SyncAlreadyCanceled&quot;- &quot;SyncFinishedCannotCancel&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorCode { get; set; }
#nullable restore
#else
        public string ErrorCode { get; set; }
#endif
        /// <summary>A place holder for a human-readable description of the error, if applicable.- &quot;sync already canceled&quot;- &quot;sync already finished&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>The id of the Model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModelId { get; set; }
#nullable restore
#else
        public string ModelId { get; set; }
#endif
        /// <summary>If no error, status will be CANCELLING, as the extract/load might take some time to cancel.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The id of the Sync.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SyncId { get; set; }
#nullable restore
#else
        public string SyncId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.CancelReverseEtlSyncForModelOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.CancelReverseEtlSyncForModelOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.CancelReverseEtlSyncForModelOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errorCode", n => { ErrorCode = n.GetStringValue(); } },
                { "errorMessage", n => { ErrorMessage = n.GetStringValue(); } },
                { "modelId", n => { ModelId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "syncId", n => { SyncId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("errorCode", ErrorCode);
            writer.WriteStringValue("errorMessage", ErrorMessage);
            writer.WriteStringValue("modelId", ModelId);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("syncId", SyncId);
        }
    }
}
#pragma warning restore CS0618
