// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Options which should be applied when segmenting traits.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ComputedTraitSummaryOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If specified, the value of this field indicates the number of days, specified from the date the audience was created, that event data will be included from when determining audience membership.If unspecified, defer to the value of `includeHistoricalData` to determine whether historical data is either entirely included or entirely excluded when determining audience membership.</summary>
        public double? BackfillDurationDays { get; set; }
        /// <summary>Determines whether anonymous users should be included when determining the computed trait value.</summary>
        public bool? IncludeAnonymousUsers { get; set; }
        /// <summary>Determines whether data prior to the computed trait being created is included when determining the computed trait value.Note that including historical data may be needed in order to properly handle the definition specified. In these cases, Segment will automatically handle including historical data and the response will return the includeHistoricalData parameter as true.</summary>
        public bool? IncludeHistoricalData { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Models.ComputedTraitSummaryOptions"/> and sets the default values.
        /// </summary>
        public ComputedTraitSummaryOptions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.ComputedTraitSummaryOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.ComputedTraitSummaryOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.ComputedTraitSummaryOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backfillDurationDays", n => { BackfillDurationDays = n.GetDoubleValue(); } },
                { "includeAnonymousUsers", n => { IncludeAnonymousUsers = n.GetBoolValue(); } },
                { "includeHistoricalData", n => { IncludeHistoricalData = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("backfillDurationDays", BackfillDurationDays);
            writer.WriteBoolValue("includeAnonymousUsers", IncludeAnonymousUsers);
            writer.WriteBoolValue("includeHistoricalData", IncludeHistoricalData);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
