// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>The subject type. Use `objectId` for Cloud Source regulations.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateWorkspaceRegulationV1InputSubjectType
    {
        [EnumMember(Value = "OBJECT_ID")]
        #pragma warning disable CS1591
        ObjectId,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER_ID")]
        #pragma warning disable CS1591
        UserId,
        #pragma warning restore CS1591
    }
}
