// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>The subject type.Note: `ANONYMOUS_ID` is only supported for limited Workspaces for Source-scoped regulations. `ANONYMOUS_ID` is only supported when regulationType is `DELETE_ARCHIVE_ONLY`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateSourceRegulationV1InputSubjectType
    {
        [EnumMember(Value = "ANONYMOUS_ID")]
        #pragma warning disable CS1591
        AnonymousId,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER_ID")]
        #pragma warning disable CS1591
        UserId,
        #pragma warning restore CS1591
    }
}
