// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Creates an insert Function instance.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateInsertFunctionInstanceAlphaInput : IParsable
    {
        /// <summary>Whether this insert Function instance should be enabled for the Destination.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Insert Function id to which this instance is associated. Note: Remove the ifnd_/ifns_ prefix from the id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FunctionId { get; set; }
#nullable restore
#else
        public string FunctionId { get; set; }
#endif
        /// <summary>The Source or Destination id to be connected.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IntegrationId { get; set; }
#nullable restore
#else
        public string IntegrationId { get; set; }
#endif
        /// <summary>Defines the display name of the insert Function instance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>An object that contains settings for this insert Function instance based on the settings present in theinsert Function class.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.CreateInsertFunctionInstanceAlphaInputSettingsProperty? Settings { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.CreateInsertFunctionInstanceAlphaInputSettingsProperty Settings { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.CreateInsertFunctionInstanceAlphaInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.CreateInsertFunctionInstanceAlphaInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.CreateInsertFunctionInstanceAlphaInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "functionId", n => { FunctionId = n.GetStringValue(); } },
                { "integrationId", n => { IntegrationId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.CreateInsertFunctionInstanceAlphaInputSettingsProperty>(global::Soenneker.Segment.OpenApiClient.Models.CreateInsertFunctionInstanceAlphaInputSettingsProperty.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("functionId", FunctionId);
            writer.WriteStringValue("integrationId", IntegrationId);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.CreateInsertFunctionInstanceAlphaInputSettingsProperty>("settings", Settings);
        }
    }
}
#pragma warning restore CS0618
