// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>The platform on which this action runs.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DestinationMetadataActionV1Platform
    {
        [EnumMember(Value = "CLOUD")]
        #pragma warning disable CS1591
        Cloud,
        #pragma warning restore CS1591
        [EnumMember(Value = "MOBILE")]
        #pragma warning disable CS1591
        Mobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEB")]
        #pragma warning disable CS1591
        Web,
        #pragma warning restore CS1591
    }
}
