// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Features that this Destination supports.Config API note: holds `browserUnbundling` fields.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DestinationMetadataV1SupportedFeatures : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether this Destination supports browser unbundling.</summary>
        public bool? BrowserUnbundling { get; set; }
        /// <summary>Whether this Destination supports public browser unbundling.</summary>
        public bool? BrowserUnbundlingPublic { get; set; }
        /// <summary>This Destination&apos;s support level for cloud mode instances.The values &apos;0&apos; and &apos;NONE&apos;, and &apos;1&apos; and &apos;SINGLE&apos; are equivalent.</summary>
        public global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataFeaturesV1CloudModeInstances? CloudModeInstances { get; set; }
        /// <summary>This Destination&apos;s support level for device mode instances.Support for multiple device mode instances is currently not planned.The values &apos;0&apos; and &apos;NONE&apos;, and &apos;1&apos; and &apos;SINGLE&apos; are equivalent.</summary>
        public global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataFeaturesV1DeviceModeInstances? DeviceModeInstances { get; set; }
        /// <summary>Whether this Destination supports replays.</summary>
        public bool? Replay { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataV1SupportedFeatures"/> and sets the default values.
        /// </summary>
        public DestinationMetadataV1SupportedFeatures()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataV1SupportedFeatures"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataV1SupportedFeatures CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataV1SupportedFeatures();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "browserUnbundling", n => { BrowserUnbundling = n.GetBoolValue(); } },
                { "browserUnbundlingPublic", n => { BrowserUnbundlingPublic = n.GetBoolValue(); } },
                { "cloudModeInstances", n => { CloudModeInstances = n.GetEnumValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataFeaturesV1CloudModeInstances>(); } },
                { "deviceModeInstances", n => { DeviceModeInstances = n.GetEnumValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataFeaturesV1DeviceModeInstances>(); } },
                { "replay", n => { Replay = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("browserUnbundling", BrowserUnbundling);
            writer.WriteBoolValue("browserUnbundlingPublic", BrowserUnbundlingPublic);
            writer.WriteEnumValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataFeaturesV1CloudModeInstances>("cloudModeInstances", CloudModeInstances);
            writer.WriteEnumValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataFeaturesV1DeviceModeInstances>("deviceModeInstances", DeviceModeInstances);
            writer.WriteBoolValue("replay", Replay);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
