// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Represents a component this Destination provides.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DestinationMetadataComponentV1 : IParsable
    {
        /// <summary>Link to the repository hosting the code for this component.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>The owner of this component. Either &apos;SEGMENT&apos; or &apos;PARTNER&apos;.</summary>
        public global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataComponentV1Owner? Owner { get; set; }
        /// <summary>The component type.</summary>
        public global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataComponentV1Type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataComponentV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataComponentV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataComponentV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetEnumValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataComponentV1Owner>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataComponentV1Type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("code", Code);
            writer.WriteEnumValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataComponentV1Owner>("owner", Owner);
            writer.WriteEnumValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataComponentV1Type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
