// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Represents a field used in configuring an action.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DestinationMetadataActionFieldV1 : IParsable
    {
        /// <summary>Whether this field allows null values.</summary>
        public bool? AllowNull { get; set; }
        /// <summary>A list of machine-readable value/label pairs to populate a static dropdown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1Choices? Choices { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1Choices Choices { get; set; }
#endif
        /// <summary>A default value that is saved the first time an action is created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1DefaultValue? DefaultValue { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1DefaultValue DefaultValue { get; set; }
#endif
        /// <summary>A human-readable description of this value. You can use Markdown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Whether this field should execute a dynamic request to fetch choices to populate a dropdown. When true, `choices` is ignored.</summary>
        public bool? Dynamic { get; set; }
        /// <summary>A unique machine-readable key for the field. Should ideally match the expected key in the action\&apos;s API request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldKey { get; set; }
#nullable restore
#else
        public string FieldKey { get; set; }
#endif
        /// <summary>Whether the action field should be hidden or not.</summary>
        public bool? Hidden { get; set; }
        /// <summary>The primary key of the field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>A human-readable label for this value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>Whether a user can provide multiples of this field.</summary>
        public bool? Multiple { get; set; }
        /// <summary>An example value displayed but not saved.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Placeholder { get; set; }
#nullable restore
#else
        public string Placeholder { get; set; }
#endif
        /// <summary>Whether this field is required.</summary>
        public bool? Required { get; set; }
        /// <summary>The order this particular field is (used in the UI for displaying the fields in a specified order).</summary>
        public double? SortOrder { get; set; }
        /// <summary>The data type for this value.</summary>
        public global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1Type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowNull", n => { AllowNull = n.GetBoolValue(); } },
                { "choices", n => { Choices = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1Choices>(global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1Choices.CreateFromDiscriminatorValue); } },
                { "defaultValue", n => { DefaultValue = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1DefaultValue>(global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1DefaultValue.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "dynamic", n => { Dynamic = n.GetBoolValue(); } },
                { "fieldKey", n => { FieldKey = n.GetStringValue(); } },
                { "hidden", n => { Hidden = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "multiple", n => { Multiple = n.GetBoolValue(); } },
                { "placeholder", n => { Placeholder = n.GetStringValue(); } },
                { "required", n => { Required = n.GetBoolValue(); } },
                { "sortOrder", n => { SortOrder = n.GetDoubleValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1Type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowNull", AllowNull);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1Choices>("choices", Choices);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1DefaultValue>("defaultValue", DefaultValue);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("dynamic", Dynamic);
            writer.WriteStringValue("fieldKey", FieldKey);
            writer.WriteBoolValue("hidden", Hidden);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("label", Label);
            writer.WriteBoolValue("multiple", Multiple);
            writer.WriteStringValue("placeholder", Placeholder);
            writer.WriteBoolValue("required", Required);
            writer.WriteDoubleValue("sortOrder", SortOrder);
            writer.WriteEnumValue<global::Soenneker.Segment.OpenApiClient.Models.DestinationMetadataActionFieldV1Type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
