// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>This Destination&apos;s support level for device mode instances.Support for multiple device mode instances is currently not planned.The values &apos;0&apos; and &apos;NONE&apos;, and &apos;1&apos; and &apos;SINGLE&apos; are equivalent.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DestinationMetadataFeaturesV1DeviceModeInstances
    {
        [EnumMember(Value = "0")]
        #pragma warning disable CS1591
        Value0,
        #pragma warning restore CS1591
        [EnumMember(Value = "1")]
        #pragma warning disable CS1591
        Value1,
        #pragma warning restore CS1591
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "SINGLE")]
        #pragma warning disable CS1591
        Single,
        #pragma warning restore CS1591
    }
}
