// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// The audience preview.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetAudiencePreviewOutputAudiencePreview : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The audience type of the preview.Possible values: USERS, ACCOUNTS, LINKED.</summary>
        public global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewAudienceType? AudienceType { get; set; }
        /// <summary>Definition that was used to calculate the audience preview.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewDefinition? Definition { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewDefinition Definition { get; set; }
#endif
        /// <summary>Explanation of why the audience preview failed. Only has a value if status is &apos;FAILED&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailureReason { get; set; }
#nullable restore
#else
        public string FailureReason { get; set; }
#endif
        /// <summary>Unique identifier for tracking and retrieving results of an audience preview.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Options that were used to calculate the audience preview.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewOptions? Options { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewOptions Options { get; set; }
#endif
        /// <summary>Sampled result membership for the audience preview. Only has a value if the status is &apos;COMPLETED&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewResult>? Results { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewResult> Results { get; set; }
#endif
        /// <summary>Result membership size for the audience preview. Only has a value if status is &apos;COMPLETED&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewSize? Size { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewSize Size { get; set; }
#endif
        /// <summary>Status for the audience preview.</summary>
        public global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Models.GetAudiencePreviewOutputAudiencePreview"/> and sets the default values.
        /// </summary>
        public GetAudiencePreviewOutputAudiencePreview()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.GetAudiencePreviewOutputAudiencePreview"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.GetAudiencePreviewOutputAudiencePreview CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.GetAudiencePreviewOutputAudiencePreview();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audienceType", n => { AudienceType = n.GetEnumValue<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewAudienceType>(); } },
                { "definition", n => { Definition = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewDefinition>(global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewDefinition.CreateFromDiscriminatorValue); } },
                { "failureReason", n => { FailureReason = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "options", n => { Options = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewOptions>(global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewOptions.CreateFromDiscriminatorValue); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewResult>(global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "size", n => { Size = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewSize>(global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewSize.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewAudienceType>("audienceType", AudienceType);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewDefinition>("definition", Definition);
            writer.WriteStringValue("failureReason", FailureReason);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewOptions>("options", Options);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewResult>("results", Results);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewSize>("size", Size);
            writer.WriteEnumValue<global::Soenneker.Segment.OpenApiClient.Models.AudiencePreviewStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
