// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Output of the Delivery Overview public API endpoints.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetDeliveryOverviewMetricsBetaOutput : IParsable
    {
        /// <summary>Represents the list of series broken down by the dimensions andtime frame requested.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.DeliveryOverviewMetricsDataset>? Dataset { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.DeliveryOverviewMetricsDataset> Dataset { get; set; }
#endif
        /// <summary>The result object used to specify the page cursor and count.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.GetDeliveryOverviewMetricsBetaOutputPagination? Pagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.GetDeliveryOverviewMetricsBetaOutputPagination Pagination { get; set; }
#endif
        /// <summary>The total number of events for the returned dataset.</summary>
        public double? Total { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.GetDeliveryOverviewMetricsBetaOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.GetDeliveryOverviewMetricsBetaOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.GetDeliveryOverviewMetricsBetaOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dataset", n => { Dataset = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.DeliveryOverviewMetricsDataset>(global::Soenneker.Segment.OpenApiClient.Models.DeliveryOverviewMetricsDataset.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pagination", n => { Pagination = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.GetDeliveryOverviewMetricsBetaOutputPagination>(global::Soenneker.Segment.OpenApiClient.Models.GetDeliveryOverviewMetricsBetaOutputPagination.CreateFromDiscriminatorValue); } },
                { "total", n => { Total = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.DeliveryOverviewMetricsDataset>("dataset", Dataset);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.GetDeliveryOverviewMetricsBetaOutputPagination>("pagination", Pagination);
            writer.WriteDoubleValue("total", Total);
        }
    }
}
#pragma warning restore CS0618
