// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// The insert Function instance.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetInsertFunctionInstanceAlphaOutputInsertFunctionInstance : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The classId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClassId { get; set; }
#nullable restore
#else
        public string ClassId { get; set; }
#endif
        /// <summary>The createdAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The encryptedSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstanceEncryptedSettings? EncryptedSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstanceEncryptedSettings EncryptedSettings { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The integrationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IntegrationId { get; set; }
#nullable restore
#else
        public string IntegrationId { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstanceSettings? Settings { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstanceSettings Settings { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstance"/> and sets the default values.
        /// </summary>
        public GetInsertFunctionInstanceAlphaOutputInsertFunctionInstance()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstance"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstance CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstance();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "classId", n => { ClassId = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "encryptedSettings", n => { EncryptedSettings = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstanceEncryptedSettings>(global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstanceEncryptedSettings.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "integrationId", n => { IntegrationId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstanceSettings>(global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstanceSettings.CreateFromDiscriminatorValue); } },
                { "updatedAt", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("classId", ClassId);
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstanceEncryptedSettings>("encryptedSettings", EncryptedSettings);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("integrationId", IntegrationId);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.GetInsertFunctionInstanceAlphaOutputInsertFunctionInstanceSettings>("settings", Settings);
            writer.WriteStringValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
