// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// The status of the reverse ETL connection job.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetReverseEtlSyncStatusOutputReverseEtlSyncStatus : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The duration of the sync.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Duration { get; set; }
#nullable restore
#else
        public string Duration { get; set; }
#endif
        /// <summary>Error message if applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>Error code indicates a fatal sync error code, if applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorCode { get; set; }
#nullable restore
#else
        public string ErrorCode { get; set; }
#endif
        /// <summary>Object with extract phase details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSyncStatusExtractPhase? ExtractPhase { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSyncStatusExtractPhase ExtractPhase { get; set; }
#endif
        /// <summary>When the sync started.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FinishedAt { get; set; }
#nullable restore
#else
        public string FinishedAt { get; set; }
#endif
        /// <summary>Object with load phase details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSyncStatusLoadPhase? LoadPhase { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSyncStatusLoadPhase LoadPhase { get; set; }
#endif
        /// <summary>The Model id of the sync.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModelId { get; set; }
#nullable restore
#else
        public string ModelId { get; set; }
#endif
        /// <summary>The Source id of the sync.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceId { get; set; }
#nullable restore
#else
        public string SourceId { get; set; }
#endif
        /// <summary>When the sync started.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartedAt { get; set; }
#nullable restore
#else
        public string StartedAt { get; set; }
#endif
        /// <summary>The id of the sync.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SyncId { get; set; }
#nullable restore
#else
        public string SyncId { get; set; }
#endif
        /// <summary>The status of the sync. It currently can be IN_PROGRESS, FAIL, SUCCESS, PARTIAL_SUCCESS.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SyncStatus { get; set; }
#nullable restore
#else
        public string SyncStatus { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Models.GetReverseEtlSyncStatusOutputReverseEtlSyncStatus"/> and sets the default values.
        /// </summary>
        public GetReverseEtlSyncStatusOutputReverseEtlSyncStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.GetReverseEtlSyncStatusOutputReverseEtlSyncStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.GetReverseEtlSyncStatusOutputReverseEtlSyncStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.GetReverseEtlSyncStatusOutputReverseEtlSyncStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "duration", n => { Duration = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "errorCode", n => { ErrorCode = n.GetStringValue(); } },
                { "extractPhase", n => { ExtractPhase = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSyncStatusExtractPhase>(global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSyncStatusExtractPhase.CreateFromDiscriminatorValue); } },
                { "finishedAt", n => { FinishedAt = n.GetStringValue(); } },
                { "loadPhase", n => { LoadPhase = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSyncStatusLoadPhase>(global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSyncStatusLoadPhase.CreateFromDiscriminatorValue); } },
                { "modelId", n => { ModelId = n.GetStringValue(); } },
                { "sourceId", n => { SourceId = n.GetStringValue(); } },
                { "startedAt", n => { StartedAt = n.GetStringValue(); } },
                { "syncId", n => { SyncId = n.GetStringValue(); } },
                { "syncStatus", n => { SyncStatus = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("duration", Duration);
            writer.WriteStringValue("error", Error);
            writer.WriteStringValue("errorCode", ErrorCode);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSyncStatusExtractPhase>("extractPhase", ExtractPhase);
            writer.WriteStringValue("finishedAt", FinishedAt);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSyncStatusLoadPhase>("loadPhase", LoadPhase);
            writer.WriteStringValue("modelId", ModelId);
            writer.WriteStringValue("sourceId", SourceId);
            writer.WriteStringValue("startedAt", StartedAt);
            writer.WriteStringValue("syncId", SyncId);
            writer.WriteStringValue("syncStatus", SyncStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
