// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Lists Versions of a Function.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListFunctionVersionsAlphaOutput : IParsable
    {
        /// <summary>Information about the pagination of this response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ListFunctionVersionsAlphaOutputPagination? Pagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ListFunctionVersionsAlphaOutputPagination Pagination { get; set; }
#endif
        /// <summary>An array of Functions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.VersionObject>? Versions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.VersionObject> Versions { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.ListFunctionVersionsAlphaOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.ListFunctionVersionsAlphaOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.ListFunctionVersionsAlphaOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "pagination", n => { Pagination = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ListFunctionVersionsAlphaOutputPagination>(global::Soenneker.Segment.OpenApiClient.Models.ListFunctionVersionsAlphaOutputPagination.CreateFromDiscriminatorValue); } },
                { "versions", n => { Versions = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.VersionObject>(global::Soenneker.Segment.OpenApiClient.Models.VersionObject.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ListFunctionVersionsAlphaOutputPagination>("pagination", Pagination);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.VersionObject>("versions", Versions);
        }
    }
}
#pragma warning restore CS0618
