// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>Field to sort by. Defaults to &apos;trait&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListTraitsSortByParameter
    {
        [EnumMember(Value = "lastSeenAt")]
        #pragma warning disable CS1591
        LastSeenAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "trait")]
        #pragma warning disable CS1591
        Trait,
        #pragma warning restore CS1591
    }
}
