// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Results containing the Selective Sync configuration for a Space Warehouse Connection.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListSelectiveSyncsFromWarehouseAndSpaceAlphaOutput : IParsable
    {
        /// <summary>Optional. Represents the enabled state of all event tables.</summary>
        public bool? EnableEventTables { get; set; }
        /// <summary>Represents a list of collections and properties synced to the Warehouse.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.SpaceWarehouseSelectiveSyncItemAlpha>? Items { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.SpaceWarehouseSelectiveSyncItemAlpha> Items { get; set; }
#endif
        /// <summary>Information about the pagination of this response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSpaceAlphaOutputPagination? Pagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSpaceAlphaOutputPagination Pagination { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSpaceAlphaOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSpaceAlphaOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSpaceAlphaOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enableEventTables", n => { EnableEventTables = n.GetBoolValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.SpaceWarehouseSelectiveSyncItemAlpha>(global::Soenneker.Segment.OpenApiClient.Models.SpaceWarehouseSelectiveSyncItemAlpha.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pagination", n => { Pagination = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSpaceAlphaOutputPagination>(global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSpaceAlphaOutputPagination.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enableEventTables", EnableEventTables);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.SpaceWarehouseSelectiveSyncItemAlpha>("items", Items);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSpaceAlphaOutputPagination>("pagination", Pagination);
        }
    }
}
#pragma warning restore CS0618
