// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>Collection to get trait values for. Defaults to &apos;users&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListSampleValuesFromTraitCollectionParameter
    {
        [EnumMember(Value = "accounts")]
        #pragma warning disable CS1591
        Accounts,
        #pragma warning restore CS1591
        [EnumMember(Value = "users")]
        #pragma warning disable CS1591
        Users,
        #pragma warning restore CS1591
    }
}
