// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Returns the Warehouses and Sources that consume a Credential. The two lists are paginatedindependently, so a caller can page through one without affecting the other.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListCredentialConsumersV1Output : IParsable
    {
        /// <summary>The Sources that use this Credential.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.SourceV1>? Sources { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.SourceV1> Sources { get; set; }
#endif
        /// <summary>Information about the pagination of the Sources list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1OutputSourcesPagination? SourcesPagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1OutputSourcesPagination SourcesPagination { get; set; }
#endif
        /// <summary>The Warehouses that use this Credential.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.WarehouseV1>? Warehouses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.WarehouseV1> Warehouses { get; set; }
#endif
        /// <summary>Information about the pagination of the Warehouses list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1OutputWarehousesPagination? WarehousesPagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1OutputWarehousesPagination WarehousesPagination { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1Output"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1Output CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1Output();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "sources", n => { Sources = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.SourceV1>(global::Soenneker.Segment.OpenApiClient.Models.SourceV1.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sourcesPagination", n => { SourcesPagination = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1OutputSourcesPagination>(global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1OutputSourcesPagination.CreateFromDiscriminatorValue); } },
                { "warehouses", n => { Warehouses = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.WarehouseV1>(global::Soenneker.Segment.OpenApiClient.Models.WarehouseV1.CreateFromDiscriminatorValue)?.AsList(); } },
                { "warehousesPagination", n => { WarehousesPagination = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1OutputWarehousesPagination>(global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1OutputWarehousesPagination.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.SourceV1>("sources", Sources);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1OutputSourcesPagination>("sourcesPagination", SourcesPagination);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.WarehouseV1>("warehouses", Warehouses);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumersV1OutputWarehousesPagination>("warehousesPagination", WarehousesPagination);
        }
    }
}
#pragma warning restore CS0618
