// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListWorkspaceRegulationsRegulationTypesParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DELETE_INTERNAL")]
        #pragma warning disable CS1591
        DeleteInternal,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETE_ONLY")]
        #pragma warning disable CS1591
        DeleteOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUPPRESS_ONLY")]
        #pragma warning disable CS1591
        SuppressOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUPPRESS_WITH_DELETE")]
        #pragma warning disable CS1591
        SuppressWithDelete,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUPPRESS_WITH_DELETE_INTERNAL")]
        #pragma warning disable CS1591
        SuppressWithDeleteInternal,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNSUPPRESS")]
        #pragma warning disable CS1591
        Unsuppress,
        #pragma warning restore CS1591
    }
}
