// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MessageSubscriptionResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Error messages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseError>? Errors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseError> Errors { get; set; }
#endif
        /// <summary>Optional subscription groups.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.UpdateGroupSubscriptionStatusResponse>? Groups { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.UpdateGroupSubscriptionStatusResponse> Groups { get; set; }
#endif
        /// <summary>Key is the phone number or email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The user subscribed, unsubscribed, or on initial status.</summary>
        public global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseStatus? Status { get; set; }
        /// <summary>Type is communication medium used. Either SMS, EMAIL or WHATSAPP.</summary>
        public global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseType? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseError>(global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseError.CreateFromDiscriminatorValue)?.AsList(); } },
                { "groups", n => { Groups = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.UpdateGroupSubscriptionStatusResponse>(global::Soenneker.Segment.OpenApiClient.Models.UpdateGroupSubscriptionStatusResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseStatus>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseError>("errors", Errors);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.UpdateGroupSubscriptionStatusResponse>("groups", Groups);
            writer.WriteStringValue("key", Key);
            writer.WriteEnumValue<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Segment.OpenApiClient.Models.MessageSubscriptionResponseType>("type", Type);
        }
    }
}
#pragma warning restore CS0618
