// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// The event delivery metric.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MetricBeta : IParsable
    {
        /// <summary>Breakdown of metrics within a metric.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.BreakdownBeta>? Breakdown { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.BreakdownBeta> Breakdown { get; set; }
#endif
        /// <summary>The name of the metric.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MetricName { get; set; }
#nullable restore
#else
        public string MetricName { get; set; }
#endif
        /// <summary>Number of occurrences of the metric.</summary>
        public double? Total { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.MetricBeta"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.MetricBeta CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.MetricBeta();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "breakdown", n => { Breakdown = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.BreakdownBeta>(global::Soenneker.Segment.OpenApiClient.Models.BreakdownBeta.CreateFromDiscriminatorValue)?.AsList(); } },
                { "metricName", n => { MetricName = n.GetStringValue(); } },
                { "total", n => { Total = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.BreakdownBeta>("breakdown", Breakdown);
            writer.WriteStringValue("metricName", MetricName);
            writer.WriteDoubleValue("total", Total);
        }
    }
}
#pragma warning restore CS0618
