// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// The most basic representation of a resource belonging to a set of permissions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PermissionResourceV1 : IParsable
    {
        /// <summary>The id of this resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The labels that further refine access to this resource. Labels are exclusive to Workspace-level permissions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.AllowedLabelBeta>? Labels { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.AllowedLabelBeta> Labels { get; set; }
#endif
        /// <summary>The type for this resource.</summary>
        public global::Soenneker.Segment.OpenApiClient.Models.PermissionResourceV1Type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.PermissionResourceV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.PermissionResourceV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.PermissionResourceV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetStringValue(); } },
                { "labels", n => { Labels = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.AllowedLabelBeta>(global::Soenneker.Segment.OpenApiClient.Models.AllowedLabelBeta.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Segment.OpenApiClient.Models.PermissionResourceV1Type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.AllowedLabelBeta>("labels", Labels);
            writer.WriteEnumValue<global::Soenneker.Segment.OpenApiClient.Models.PermissionResourceV1Type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
