// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Defines a Profiles data Warehouse used as a Destination for Segment data.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProfilesWarehouseAlpha : IParsable
    {
        /// <summary>When set to true, this Warehouse receives data.</summary>
        public bool? Enabled { get; set; }
        /// <summary>The id of the Warehouse.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The metadata for the Warehouse.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlphaMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlphaMetadata Metadata { get; set; }
#endif
        /// <summary>The custom schema name that Segment uses on the Warehouse side.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SchemaName { get; set; }
#nullable restore
#else
        public string SchemaName { get; set; }
#endif
        /// <summary>The settings associated with this Warehouse.Common settings are connection-related configuration used to connect to it, for example host, username, and port.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlphaSettings? Settings { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlphaSettings Settings { get; set; }
#endif
        /// <summary>The Space id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpaceId { get; set; }
#nullable restore
#else
        public string SpaceId { get; set; }
#endif
        /// <summary>The id of the Workspace that owns this Warehouse.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceId { get; set; }
#nullable restore
#else
        public string WorkspaceId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlpha"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlpha CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlpha();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlphaMetadata>(global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlphaMetadata.CreateFromDiscriminatorValue); } },
                { "schemaName", n => { SchemaName = n.GetStringValue(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlphaSettings>(global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlphaSettings.CreateFromDiscriminatorValue); } },
                { "spaceId", n => { SpaceId = n.GetStringValue(); } },
                { "workspaceId", n => { WorkspaceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlphaMetadata>("metadata", Metadata);
            writer.WriteStringValue("schemaName", SchemaName);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ProfilesWarehouseAlphaSettings>("settings", Settings);
            writer.WriteStringValue("spaceId", SpaceId);
            writer.WriteStringValue("workspaceId", WorkspaceId);
        }
    }
}
#pragma warning restore CS0618
