// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlCronScheduleConfig"/>, <see cref="global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlDbtCloudScheduleConfig"/>, <see cref="global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlPeriodicScheduleConfig"/>, <see cref="global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSpecificTimeScheduleConfig"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReverseEtlScheduleDefinitionConfig : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlCronScheduleConfig"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlCronScheduleConfig? ReverseEtlCronScheduleConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlCronScheduleConfig ReverseEtlCronScheduleConfig { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlDbtCloudScheduleConfig"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlDbtCloudScheduleConfig? ReverseEtlDbtCloudScheduleConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlDbtCloudScheduleConfig ReverseEtlDbtCloudScheduleConfig { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlPeriodicScheduleConfig"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlPeriodicScheduleConfig? ReverseEtlPeriodicScheduleConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlPeriodicScheduleConfig ReverseEtlPeriodicScheduleConfig { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSpecificTimeScheduleConfig"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSpecificTimeScheduleConfig? ReverseEtlSpecificTimeScheduleConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSpecificTimeScheduleConfig ReverseEtlSpecificTimeScheduleConfig { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlScheduleDefinitionConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlScheduleDefinitionConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlScheduleDefinitionConfig();
            result.ReverseEtlCronScheduleConfig = new global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlCronScheduleConfig();
            result.ReverseEtlDbtCloudScheduleConfig = new global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlDbtCloudScheduleConfig();
            result.ReverseEtlPeriodicScheduleConfig = new global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlPeriodicScheduleConfig();
            result.ReverseEtlSpecificTimeScheduleConfig = new global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlSpecificTimeScheduleConfig();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ReverseEtlCronScheduleConfig != null || ReverseEtlDbtCloudScheduleConfig != null || ReverseEtlPeriodicScheduleConfig != null || ReverseEtlSpecificTimeScheduleConfig != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ReverseEtlCronScheduleConfig, ReverseEtlDbtCloudScheduleConfig, ReverseEtlPeriodicScheduleConfig, ReverseEtlSpecificTimeScheduleConfig);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.ReverseEtlCronScheduleConfig>(null, ReverseEtlCronScheduleConfig, ReverseEtlDbtCloudScheduleConfig, ReverseEtlPeriodicScheduleConfig, ReverseEtlSpecificTimeScheduleConfig);
        }
    }
}
#pragma warning restore CS0618
