// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Track settings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SourceSettingsOutputV1Track : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Allow track event on violations.Config API note: equal to `allowTrackEventOnViolations`.</summary>
        public bool? AllowEventOnViolations { get; set; }
        /// <summary>Enable to allow track properties on violations.Config API note: equal to `allowTrackEventPropertiesOnViolations`.</summary>
        public bool? AllowPropertiesOnViolations { get; set; }
        /// <summary>Enable to allow unplanned track event properties.Config API note: equal to `allowUnplannedTrackEventProperties`.</summary>
        public bool? AllowUnplannedEventProperties { get; set; }
        /// <summary>Enable to allow unplanned track events.Config API note: equal to `allowUnplannedTrackEvents`.</summary>
        public bool? AllowUnplannedEvents { get; set; }
        /// <summary>The common track event on violations.Config API note: equal to `commonTrackEventOnViolations`.</summary>
        public global::Soenneker.Segment.OpenApiClient.Models.TrackSourceSettingsV1CommonEventOnViolations? CommonEventOnViolations { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Models.SourceSettingsOutputV1Track"/> and sets the default values.
        /// </summary>
        public SourceSettingsOutputV1Track()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.SourceSettingsOutputV1Track"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.SourceSettingsOutputV1Track CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.SourceSettingsOutputV1Track();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowEventOnViolations", n => { AllowEventOnViolations = n.GetBoolValue(); } },
                { "allowPropertiesOnViolations", n => { AllowPropertiesOnViolations = n.GetBoolValue(); } },
                { "allowUnplannedEventProperties", n => { AllowUnplannedEventProperties = n.GetBoolValue(); } },
                { "allowUnplannedEvents", n => { AllowUnplannedEvents = n.GetBoolValue(); } },
                { "commonEventOnViolations", n => { CommonEventOnViolations = n.GetEnumValue<global::Soenneker.Segment.OpenApiClient.Models.TrackSourceSettingsV1CommonEventOnViolations>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowEventOnViolations", AllowEventOnViolations);
            writer.WriteBoolValue("allowPropertiesOnViolations", AllowPropertiesOnViolations);
            writer.WriteBoolValue("allowUnplannedEventProperties", AllowUnplannedEventProperties);
            writer.WriteBoolValue("allowUnplannedEvents", AllowUnplannedEvents);
            writer.WriteEnumValue<global::Soenneker.Segment.OpenApiClient.Models.TrackSourceSettingsV1CommonEventOnViolations>("commonEventOnViolations", CommonEventOnViolations);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
