// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Input to update an activation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateActivationForAudienceAlphaInput : IParsable
    {
        /// <summary>Activation name. For Warehouse Destinations, this is used as the table name.Omit this field to leave the name unchanged. An empty string is ignored rather than applied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActivationName { get; set; }
#nullable restore
#else
        public string ActivationName { get; set; }
#endif
        /// <summary>Defines the specific action and data mapping for the Destination. Only applicable for Action Destinations.Action id: Specifies which action to perform on the Destination (for example: add contact, update list).Settings/Mapping: Defines how event data (including personalization traits) populates specific fields in the Destination.Use the List Supported Destinations from Audience endpoint to find available action ids and the specific Destination fields you can map.On update, settings are applied one field at a time. A field that is not supplied keeps its stored value, and a field that is supplied has its value replaced outright.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInputDestinationMapping? DestinationMapping { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInputDestinationMapping DestinationMapping { get; set; }
#endif
        /// <summary>Optional human-readable label for the activation. Only supported for Warehouse Destinations. Send null to clear. When omitted, the activationName is used as the label.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Determines whether an activation is enabled.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Determines whether to perform a full resync after the update. If true, the entire audience is resent to the Destination using the updated configuration. If false, the update applies only to future syncs.</summary>
        public bool? PerformResync { get; set; }
        /// <summary>The data points used to enrich the event. Defines which profile traits and/or entity properties are included in the event sent to the Destination.For Action Destinations, any traits or properties specified here must also be included in the destinationMapping to define which Destination fields should be populated.On update, profile and entities are evaluated separately. Omit either one to leave it unchanged.A value that is supplied replaces the stored value outright instead of being combined with it, so include every trait or property that should remain. Supplying an empty entities array removes all entities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInputPersonalization? Personalization { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInputPersonalization Personalization { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activationName", n => { ActivationName = n.GetStringValue(); } },
                { "destinationMapping", n => { DestinationMapping = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInputDestinationMapping>(global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInputDestinationMapping.CreateFromDiscriminatorValue); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "performResync", n => { PerformResync = n.GetBoolValue(); } },
                { "personalization", n => { Personalization = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInputPersonalization>(global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInputPersonalization.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("activationName", ActivationName);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInputDestinationMapping>("destinationMapping", DestinationMapping);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteBoolValue("performResync", PerformResync);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateActivationForAudienceAlphaInputPersonalization>("personalization", Personalization);
        }
    }
}
#pragma warning restore CS0618
