// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>Status of the update operation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateSelectiveSyncForWarehouseAndSpaceAlphaOutputStatus
    {
        [EnumMember(Value = "UNCHANGED")]
        #pragma warning disable CS1591
        Unchanged,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPDATED")]
        #pragma warning disable CS1591
        Updated,
        #pragma warning restore CS1591
    }
}
