// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Input to update a Source&apos;s settings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateSchemaSettingsInSourceV1Input : IParsable
    {
        /// <summary>Source id to forward blocked events to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForwardingBlockedEventsTo { get; set; }
#nullable restore
#else
        public string ForwardingBlockedEventsTo { get; set; }
#endif
        /// <summary>Source id to forward violations to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForwardingViolationsTo { get; set; }
#nullable restore
#else
        public string ForwardingViolationsTo { get; set; }
#endif
        /// <summary>Group settings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputGroup? Group { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputGroup Group { get; set; }
#endif
        /// <summary>Identify settings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputIdentify? Identify { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputIdentify Identify { get; set; }
#endif
        /// <summary>Track settings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputTrack? Track { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputTrack Track { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1Input"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1Input CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1Input();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "forwardingBlockedEventsTo", n => { ForwardingBlockedEventsTo = n.GetStringValue(); } },
                { "forwardingViolationsTo", n => { ForwardingViolationsTo = n.GetStringValue(); } },
                { "group", n => { Group = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputGroup>(global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputGroup.CreateFromDiscriminatorValue); } },
                { "identify", n => { Identify = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputIdentify>(global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputIdentify.CreateFromDiscriminatorValue); } },
                { "track", n => { Track = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputTrack>(global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputTrack.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("forwardingBlockedEventsTo", ForwardingBlockedEventsTo);
            writer.WriteStringValue("forwardingViolationsTo", ForwardingViolationsTo);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputGroup>("group", Group);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputIdentify>("identify", Identify);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateSchemaSettingsInSourceV1InputTrack>("track", Track);
        }
    }
}
#pragma warning restore CS0618
