// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Input to Update a Destination for an Audience. At least one of idSyncConfiguration or connectionSettings must be supplied, otherwise the request returns a 400 error.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateDestinationForAudienceAlphaInput : IParsable
    {
        /// <summary>The settings that a Destination requires to create audiences on a third-party platform.The supplied object replaces the stored settings outright, so include every setting that should remain. Settings that are omitted are removed.An empty object is treated the same as omitting the field and leaves the stored settings unchanged.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateDestinationForAudienceAlphaInputConnectionSettings? ConnectionSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.UpdateDestinationForAudienceAlphaInputConnectionSettings ConnectionSettings { get; set; }
#endif
        /// <summary>Identifier sync configuration - array of external IDs to sync with their strategies. Maximum 5 items allowed.The supplied array replaces the entire stored configuration, so include every external id that should remain. Omitting mapTo on an entry clears any value stored for it.An empty array is treated the same as omitting the field and leaves the stored configuration unchanged.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Segment.OpenApiClient.Models.IdSyncConfigurationInput>? IdSyncConfiguration { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Segment.OpenApiClient.Models.IdSyncConfigurationInput> IdSyncConfiguration { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.UpdateDestinationForAudienceAlphaInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.UpdateDestinationForAudienceAlphaInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.UpdateDestinationForAudienceAlphaInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "connectionSettings", n => { ConnectionSettings = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateDestinationForAudienceAlphaInputConnectionSettings>(global::Soenneker.Segment.OpenApiClient.Models.UpdateDestinationForAudienceAlphaInputConnectionSettings.CreateFromDiscriminatorValue); } },
                { "idSyncConfiguration", n => { IdSyncConfiguration = n.GetCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.IdSyncConfigurationInput>(global::Soenneker.Segment.OpenApiClient.Models.IdSyncConfigurationInput.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.UpdateDestinationForAudienceAlphaInputConnectionSettings>("connectionSettings", ConnectionSettings);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Segment.OpenApiClient.Models.IdSyncConfigurationInput>("idSyncConfiguration", IdSyncConfiguration);
        }
    }
}
#pragma warning restore CS0618
