// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>The type for this Tracking Plan rule.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpsertRuleV1Type
    {
        [EnumMember(Value = "COMMON")]
        #pragma warning disable CS1591
        Common,
        #pragma warning restore CS1591
        [EnumMember(Value = "GROUP")]
        #pragma warning disable CS1591
        Group,
        #pragma warning restore CS1591
        [EnumMember(Value = "IDENTIFY")]
        #pragma warning disable CS1591
        Identify,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAGE")]
        #pragma warning disable CS1591
        Page,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCREEN")]
        #pragma warning disable CS1591
        Screen,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRACK")]
        #pragma warning disable CS1591
        Track,
        #pragma warning restore CS1591
    }
}
