// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Segment.OpenApiClient.Models
{
    /// <summary>
    /// Represents an entry in the Warehouse Selective Sync schema for a Warehouse and Source pair.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WarehouseSelectiveSyncItemV1 : IParsable
    {
        /// <summary>The collection within the Source.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Collection { get; set; }
#nullable restore
#else
        public string Collection { get; set; }
#endif
        /// <summary>Whether this Selective Sync item is enabled.</summary>
        public bool? Enabled { get; set; }
        /// <summary>A map that contains the properties within the collection to which the Warehouse should sync.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Segment.OpenApiClient.Models.WarehouseSelectiveSyncItemV1PropertiesProperty? Properties { get; set; }
#nullable restore
#else
        public global::Soenneker.Segment.OpenApiClient.Models.WarehouseSelectiveSyncItemV1PropertiesProperty Properties { get; set; }
#endif
        /// <summary>The Source id attached to this Warehouse.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceId { get; set; }
#nullable restore
#else
        public string SourceId { get; set; }
#endif
        /// <summary>The id of the Warehouse this sync belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WarehouseId { get; set; }
#nullable restore
#else
        public string WarehouseId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.WarehouseSelectiveSyncItemV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Segment.OpenApiClient.Models.WarehouseSelectiveSyncItemV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Segment.OpenApiClient.Models.WarehouseSelectiveSyncItemV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collection", n => { Collection = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "properties", n => { Properties = n.GetObjectValue<global::Soenneker.Segment.OpenApiClient.Models.WarehouseSelectiveSyncItemV1PropertiesProperty>(global::Soenneker.Segment.OpenApiClient.Models.WarehouseSelectiveSyncItemV1PropertiesProperty.CreateFromDiscriminatorValue); } },
                { "sourceId", n => { SourceId = n.GetStringValue(); } },
                { "warehouseId", n => { WarehouseId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("collection", Collection);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteObjectValue<global::Soenneker.Segment.OpenApiClient.Models.WarehouseSelectiveSyncItemV1PropertiesProperty>("properties", Properties);
            writer.WriteStringValue("sourceId", SourceId);
            writer.WriteStringValue("warehouseId", WarehouseId);
        }
    }
}
#pragma warning restore CS0618
