// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Segment.OpenApiClient.Catalog.Destinations;
using Soenneker.Segment.OpenApiClient.Catalog.Sources;
using Soenneker.Segment.OpenApiClient.Catalog.Warehouses;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Segment.OpenApiClient.Catalog
{
    /// <summary>
    /// Builds and executes requests for operations under \catalog
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CatalogRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The destinations property</summary>
        public global::Soenneker.Segment.OpenApiClient.Catalog.Destinations.DestinationsRequestBuilder Destinations
        {
            get => new global::Soenneker.Segment.OpenApiClient.Catalog.Destinations.DestinationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sources property</summary>
        public global::Soenneker.Segment.OpenApiClient.Catalog.Sources.SourcesRequestBuilder Sources
        {
            get => new global::Soenneker.Segment.OpenApiClient.Catalog.Sources.SourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The warehouses property</summary>
        public global::Soenneker.Segment.OpenApiClient.Catalog.Warehouses.WarehousesRequestBuilder Warehouses
        {
            get => new global::Soenneker.Segment.OpenApiClient.Catalog.Warehouses.WarehousesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Catalog.CatalogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CatalogRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Catalog.CatalogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CatalogRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
