// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Segment.OpenApiClient.DeliveryOverview.FailedDelivery;
using Soenneker.Segment.OpenApiClient.DeliveryOverview.FailedOnIngest;
using Soenneker.Segment.OpenApiClient.DeliveryOverview.FilteredAtDestination;
using Soenneker.Segment.OpenApiClient.DeliveryOverview.FilteredAtSource;
using Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfulDelivery;
using Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Segment.OpenApiClient.DeliveryOverview
{
    /// <summary>
    /// Builds and executes requests for operations under \delivery-overview
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeliveryOverviewRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The failedDelivery property</summary>
        public global::Soenneker.Segment.OpenApiClient.DeliveryOverview.FailedDelivery.FailedDeliveryRequestBuilder FailedDelivery
        {
            get => new global::Soenneker.Segment.OpenApiClient.DeliveryOverview.FailedDelivery.FailedDeliveryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The failedOnIngest property</summary>
        public global::Soenneker.Segment.OpenApiClient.DeliveryOverview.FailedOnIngest.FailedOnIngestRequestBuilder FailedOnIngest
        {
            get => new global::Soenneker.Segment.OpenApiClient.DeliveryOverview.FailedOnIngest.FailedOnIngestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filteredAtDestination property</summary>
        public global::Soenneker.Segment.OpenApiClient.DeliveryOverview.FilteredAtDestination.FilteredAtDestinationRequestBuilder FilteredAtDestination
        {
            get => new global::Soenneker.Segment.OpenApiClient.DeliveryOverview.FilteredAtDestination.FilteredAtDestinationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filteredAtSource property</summary>
        public global::Soenneker.Segment.OpenApiClient.DeliveryOverview.FilteredAtSource.FilteredAtSourceRequestBuilder FilteredAtSource
        {
            get => new global::Soenneker.Segment.OpenApiClient.DeliveryOverview.FilteredAtSource.FilteredAtSourceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The successfulDelivery property</summary>
        public global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfulDelivery.SuccessfulDeliveryRequestBuilder SuccessfulDelivery
        {
            get => new global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfulDelivery.SuccessfulDeliveryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The successfullyReceived property</summary>
        public global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived.SuccessfullyReceivedRequestBuilder SuccessfullyReceived
        {
            get => new global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived.SuccessfullyReceivedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.DeliveryOverview.DeliveryOverviewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeliveryOverviewRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/delivery-overview", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.DeliveryOverview.DeliveryOverviewRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeliveryOverviewRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/delivery-overview", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
