// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Segment.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Segment.OpenApiClient.Credentials.Item.Consumers
{
    /// <summary>
    /// Builds and executes requests for operations under \credentials\{credentialId}\consumers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConsumersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Credentials.Item.Consumers.ConsumersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConsumersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/credentials/{credentialId}/consumers{?sourcesPagination*,warehousesPagination*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Credentials.Item.Consumers.ConsumersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConsumersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/credentials/{credentialId}/consumers{?sourcesPagination*,warehousesPagination*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the Warehouses and Sources that use a Credential.This endpoint requires the user to have at least the following permission(s):  * Workspace Owner * Warehouse Admin * Source Admin * Entities Admin * Unify and Engage Admin
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumers200SegmentV1JsonResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumers200SegmentV1JsonResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Credentials.Item.Consumers.ConsumersRequestBuilder.ConsumersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumers200SegmentV1JsonResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Credentials.Item.Consumers.ConsumersRequestBuilder.ConsumersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumers200SegmentV1JsonResponse>(requestInfo, global::Soenneker.Segment.OpenApiClient.Models.ListCredentialConsumers200SegmentV1JsonResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the Warehouses and Sources that use a Credential.This endpoint requires the user to have at least the following permission(s):  * Workspace Owner * Warehouse Admin * Source Admin * Entities Admin * Unify and Engage Admin
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Credentials.Item.Consumers.ConsumersRequestBuilder.ConsumersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Credentials.Item.Consumers.ConsumersRequestBuilder.ConsumersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/vnd.segment.v1+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Credentials.Item.Consumers.ConsumersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Segment.OpenApiClient.Credentials.Item.Consumers.ConsumersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Segment.OpenApiClient.Credentials.Item.Consumers.ConsumersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the Warehouses and Sources that use a Credential.This endpoint requires the user to have at least the following permission(s):  * Workspace Owner * Warehouse Admin * Source Admin * Entities Admin * Unify and Engage Admin
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConsumersRequestBuilderGetQueryParameters 
        {
            /// <summary>Defines the pagination parameters for the list of Sources.This parameter exists in v1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sourcesPagination")]
            public string? SourcesPagination { get; set; }
#nullable restore
#else
            [QueryParameter("sourcesPagination")]
            public string SourcesPagination { get; set; }
#endif
            /// <summary>Defines the pagination parameters for the list of Warehouses.This parameter exists in v1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("warehousesPagination")]
            public string? WarehousesPagination { get; set; }
#nullable restore
#else
            [QueryParameter("warehousesPagination")]
            public string WarehousesPagination { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
