// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Segment.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Segment.OpenApiClient.Warehouses.Item.ConnectedSources.Item.SelectiveSyncs
{
    /// <summary>
    /// Builds and executes requests for operations under \warehouses\{warehouseId}\connected-sources\{sourceId}\selective-syncs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SelectiveSyncsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Warehouses.Item.ConnectedSources.Item.SelectiveSyncs.SelectiveSyncsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SelectiveSyncsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/warehouses/{warehouseId}/connected-sources/{sourceId}/selective-syncs{?pagination*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Warehouses.Item.ConnectedSources.Item.SelectiveSyncs.SelectiveSyncsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SelectiveSyncsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/warehouses/{warehouseId}/connected-sources/{sourceId}/selective-syncs{?pagination*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the schema for a Warehouse, including Sources, Collections, and Properties.The rate limit for this endpoint is 2 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSource200SegmentV1JsonResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSource200SegmentV1JsonResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Warehouses.Item.ConnectedSources.Item.SelectiveSyncs.SelectiveSyncsRequestBuilder.SelectiveSyncsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSource200SegmentV1JsonResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Warehouses.Item.ConnectedSources.Item.SelectiveSyncs.SelectiveSyncsRequestBuilder.SelectiveSyncsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSource200SegmentV1JsonResponse>(requestInfo, global::Soenneker.Segment.OpenApiClient.Models.ListSelectiveSyncsFromWarehouseAndSource200SegmentV1JsonResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the schema for a Warehouse, including Sources, Collections, and Properties.The rate limit for this endpoint is 2 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Warehouses.Item.ConnectedSources.Item.SelectiveSyncs.SelectiveSyncsRequestBuilder.SelectiveSyncsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Warehouses.Item.ConnectedSources.Item.SelectiveSyncs.SelectiveSyncsRequestBuilder.SelectiveSyncsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/vnd.segment.v1+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Warehouses.Item.ConnectedSources.Item.SelectiveSyncs.SelectiveSyncsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Segment.OpenApiClient.Warehouses.Item.ConnectedSources.Item.SelectiveSyncs.SelectiveSyncsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Segment.OpenApiClient.Warehouses.Item.ConnectedSources.Item.SelectiveSyncs.SelectiveSyncsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the schema for a Warehouse, including Sources, Collections, and Properties.The rate limit for this endpoint is 2 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SelectiveSyncsRequestBuilderGetQueryParameters 
        {
            /// <summary>Defines the pagination parameters.This parameter exists in v1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pagination")]
            public string? Pagination { get; set; }
#nullable restore
#else
            [QueryParameter("pagination")]
            public string Pagination { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
