// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Segment.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived
{
    /// <summary>
    /// Builds and executes requests for operations under \delivery-overview\successfully-received
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SuccessfullyReceivedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived.SuccessfullyReceivedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuccessfullyReceivedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/delivery-overview/successfully-received?endTime={endTime}&granularity={granularity}&sourceId={sourceId}&startTime={startTime}{&filter*,groupBy*,pagination*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived.SuccessfullyReceivedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuccessfullyReceivedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/delivery-overview/successfully-received?endTime={endTime}&granularity={granularity}&sourceId={sourceId}&startTime={startTime}{&filter*,groupBy*,pagination*}", rawUrl)
        {
        }
        /// <summary>
        /// Get events that were successfully received by Segment.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.GetIngressSuccessMetricsFromDeliveryOverview200SegmentV1BetaJsonResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Segment.OpenApiClient.Models.GetIngressSuccessMetricsFromDeliveryOverview200SegmentV1BetaJsonResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived.SuccessfullyReceivedRequestBuilder.SuccessfullyReceivedRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Segment.OpenApiClient.Models.GetIngressSuccessMetricsFromDeliveryOverview200SegmentV1BetaJsonResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived.SuccessfullyReceivedRequestBuilder.SuccessfullyReceivedRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Segment.OpenApiClient.Models.GetIngressSuccessMetricsFromDeliveryOverview200SegmentV1BetaJsonResponse>(requestInfo, global::Soenneker.Segment.OpenApiClient.Models.GetIngressSuccessMetricsFromDeliveryOverview200SegmentV1BetaJsonResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get events that were successfully received by Segment.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived.SuccessfullyReceivedRequestBuilder.SuccessfullyReceivedRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived.SuccessfullyReceivedRequestBuilder.SuccessfullyReceivedRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/vnd.segment.v1beta+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived.SuccessfullyReceivedRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived.SuccessfullyReceivedRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Segment.OpenApiClient.DeliveryOverview.SuccessfullyReceived.SuccessfullyReceivedRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get events that were successfully received by Segment.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SuccessfullyReceivedRequestBuilderGetQueryParameters 
        {
            /// <summary>The ISO8601 formatted timestamp corresponding to theend of the requested time frame, noninclusive.This parameter exists in beta.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("endTime")]
            public string? EndTime { get; set; }
#nullable restore
#else
            [QueryParameter("endTime")]
            public string EndTime { get; set; }
#endif
            /// <summary>An optional filter for `event Name`, `event Type`, and/or `app Version` that can be applied in addition to a `group By`.This parameter exists in beta.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
            /// <summary>The size of each bucket in the requested window.Based on the granularity chosen, there are restrictions on the time range you can query:**Minute**:- Max time range: 4 hours- Oldest possible start time: 48 hours in the past**Hour**:- Max Time range: 14 days- Oldest possible start time: 30 days in the past**Day**:- Max time range: 30 days- Oldest possible start time: 30 days in the pastThis parameter exists in beta.</summary>
            [QueryParameter("granularity")]
            public global::Soenneker.Segment.OpenApiClient.Models.GetIngressSuccessMetricsFromDeliveryOverviewGranularityParameter? Granularity { get; set; }
            /// <summary>A comma-delimited list of strings representing one or more dimensionsto group the result by.  Valid options are:`event Name`, `event Type`, and/or `app Version`.This parameter exists in beta.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("groupBy")]
            public string[]? GroupBy { get; set; }
#nullable restore
#else
            [QueryParameter("groupBy")]
            public string[] GroupBy { get; set; }
#endif
            /// <summary>Optional params to specify the page cursor and count.This parameter exists in beta.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pagination")]
            public string? Pagination { get; set; }
#nullable restore
#else
            [QueryParameter("pagination")]
            public string Pagination { get; set; }
#endif
            /// <summary>The sourceId for the Workspace.This parameter exists in beta.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sourceId")]
            public string? SourceId { get; set; }
#nullable restore
#else
            [QueryParameter("sourceId")]
            public string SourceId { get; set; }
#endif
            /// <summary>The ISO8601 formatted timestamp corresponding to thebeginning of the requested time frame, inclusive.This parameter exists in beta.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("startTime")]
            public string? StartTime { get; set; }
#nullable restore
#else
            [QueryParameter("startTime")]
            public string StartTime { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
