// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Segment.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Segment.OpenApiClient.Events.Volume
{
    /// <summary>
    /// Builds and executes requests for operations under \events\volume
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VolumeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Events.Volume.VolumeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VolumeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events/volume?endTime={endTime}&granularity={granularity}&startTime={startTime}{&appVersion*,eventName*,eventType*,groupBy*,pagination*,sourceId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Events.Volume.VolumeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VolumeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events/volume?endTime={endTime}&granularity={granularity}&startTime={startTime}{&appVersion*,eventName*,eventType*,groupBy*,pagination*,sourceId*}", rawUrl)
        {
        }
        /// <summary>
        /// Enumerates the Workspace event volumes over time in minute increments.The rate limit for this endpoint is 60 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.GetEventsVolumeFromWorkspace200SegmentV1JsonResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Segment.OpenApiClient.Models.GetEventsVolumeFromWorkspace200SegmentV1JsonResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Events.Volume.VolumeRequestBuilder.VolumeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Segment.OpenApiClient.Models.GetEventsVolumeFromWorkspace200SegmentV1JsonResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Events.Volume.VolumeRequestBuilder.VolumeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Segment.OpenApiClient.Models.GetEventsVolumeFromWorkspace200SegmentV1JsonResponse>(requestInfo, global::Soenneker.Segment.OpenApiClient.Models.GetEventsVolumeFromWorkspace200SegmentV1JsonResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Enumerates the Workspace event volumes over time in minute increments.The rate limit for this endpoint is 60 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Events.Volume.VolumeRequestBuilder.VolumeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Segment.OpenApiClient.Events.Volume.VolumeRequestBuilder.VolumeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/vnd.segment.v1+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Events.Volume.VolumeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Segment.OpenApiClient.Events.Volume.VolumeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Segment.OpenApiClient.Events.Volume.VolumeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Enumerates the Workspace event volumes over time in minute increments.The rate limit for this endpoint is 60 requests per minute, which is lower than the default due to access pattern restrictions. Once reached, this endpoint will respond with the 429 HTTP status code with headers indicating the limit parameters. See [Rate Limiting](/#tag/Rate-Limits) for more information.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class VolumeRequestBuilderGetQueryParameters 
        {
            /// <summary>A list of strings which filters the results to the givenAppVersions.This parameter exists in v1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("appVersion")]
            public string[]? AppVersion { get; set; }
#nullable restore
#else
            [QueryParameter("appVersion")]
            public string[] AppVersion { get; set; }
#endif
            /// <summary>The ISO8601 formatted timestamp that corresponds to theend of the requested time frame, noninclusive.Segment recommends that you lag queries 1 minute behind clock time to reducethe risk for latency to impact the counts.This parameter exists in v1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("endTime")]
            public string? EndTime { get; set; }
#nullable restore
#else
            [QueryParameter("endTime")]
            public string EndTime { get; set; }
#endif
            /// <summary>A list of strings which filters the results to the givenEventNames.This parameter exists in v1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("eventName")]
            public string[]? EventName { get; set; }
#nullable restore
#else
            [QueryParameter("eventName")]
            public string[] EventName { get; set; }
#endif
            /// <summary>A list of strings which filters the results to the givenEventTypes.This parameter exists in v1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("eventType")]
            public string[]? EventType { get; set; }
#nullable restore
#else
            [QueryParameter("eventType")]
            public string[] EventType { get; set; }
#endif
            /// <summary>The size of each bucket in the requested window.This parameter exists in v1.</summary>
            [QueryParameter("granularity")]
            public global::Soenneker.Segment.OpenApiClient.Models.GetEventsVolumeFromWorkspaceGranularityParameter? Granularity { get; set; }
            /// <summary>A comma-delimited list of strings that represents the dimensionsto group the result by. The options are:`eventName`, `eventType` and `source`.This parameter exists in v1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("groupBy")]
            public string[]? GroupBy { get; set; }
#nullable restore
#else
            [QueryParameter("groupBy")]
            public string[] GroupBy { get; set; }
#endif
            /// <summary>Pagination input for event volume by Workspace.This parameter exists in v1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pagination")]
            public string? Pagination { get; set; }
#nullable restore
#else
            [QueryParameter("pagination")]
            public string Pagination { get; set; }
#endif
            /// <summary>A list of strings which filters the results to the givenSourceIds.This parameter exists in v1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sourceId")]
            public string[]? SourceId { get; set; }
#nullable restore
#else
            [QueryParameter("sourceId")]
            public string[] SourceId { get; set; }
#endif
            /// <summary>The ISO8601 formatted timestamp that corresponds to thebeginning of the requested time frame, inclusive.This parameter exists in v1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("startTime")]
            public string? StartTime { get; set; }
#nullable restore
#else
            [QueryParameter("startTime")]
            public string StartTime { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
