// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Segment.OpenApiClient.Models;
using Soenneker.Segment.OpenApiClient.Sources.Item.Writekey.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Segment.OpenApiClient.Sources.Item.Writekey
{
    /// <summary>
    /// Builds and executes requests for operations under \sources\{sourceId}\writekey
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WritekeyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Segment.OpenApiClient.sources.item.writekey.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Sources.Item.Writekey.Item.WithWriteKeyItemRequestBuilder"/></returns>
        public global::Soenneker.Segment.OpenApiClient.Sources.Item.Writekey.Item.WithWriteKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("writeKey", position);
                return new global::Soenneker.Segment.OpenApiClient.Sources.Item.Writekey.Item.WithWriteKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Sources.Item.Writekey.WritekeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WritekeyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sources/{sourceId}/writekey", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Sources.Item.Writekey.WritekeyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WritekeyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sources/{sourceId}/writekey", rawUrl)
        {
        }
        /// <summary>
        /// Creates a new Write Key for the Source.• When called, this endpoint may generate the `Source Modified` event in the [audit trail](/tag/Audit-Trail).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Models.CreateWriteKeyForSource200SegmentV1AlphaJsonResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Segment.OpenApiClient.Models.CreateWriteKeyForSource200SegmentV1AlphaJsonResponse?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Segment.OpenApiClient.Models.CreateWriteKeyForSource200SegmentV1AlphaJsonResponse> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Segment.OpenApiClient.Models.RequestErrorEnvelope.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Segment.OpenApiClient.Models.CreateWriteKeyForSource200SegmentV1AlphaJsonResponse>(requestInfo, global::Soenneker.Segment.OpenApiClient.Models.CreateWriteKeyForSource200SegmentV1AlphaJsonResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new Write Key for the Source.• When called, this endpoint may generate the `Source Modified` event in the [audit trail](/tag/Audit-Trail).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/vnd.segment.v1alpha+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Segment.OpenApiClient.Sources.Item.Writekey.WritekeyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Segment.OpenApiClient.Sources.Item.Writekey.WritekeyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Segment.OpenApiClient.Sources.Item.Writekey.WritekeyRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
