// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Segment.OpenApiClient.Group.Item.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Segment.OpenApiClient.Group.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \group\{userGroupId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUserGroupItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The users property</summary>
        public global::Soenneker.Segment.OpenApiClient.Group.Item.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Segment.OpenApiClient.Group.Item.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Group.Item.WithUserGroupItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserGroupItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/group/{userGroupId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Segment.OpenApiClient.Group.Item.WithUserGroupItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserGroupItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/group/{userGroupId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
